# Generated by Django 2.2.7 on 2019-11-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('question_1', models.CharField(default='What is your favorite color?', max_length=100)),
                ('question_2', models.CharField(default='Who is your best friend?', max_length=100)),
                ('answer_1', models.CharField(max_length=20)),
                ('answer_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(default='NA', max_length=50)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('question_1', models.CharField(default='NA', max_length=100)),
                ('question_2', models.CharField(default='NA', max_length=100)),
                ('answer_1', models.CharField(max_length=20)),
                ('answer_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='NA', max_length=15)),
                ('start_time', models.TimeField()),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.Kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(default='N/A', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_vegan', models.BooleanField(default=False)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.Kitchen')),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.Provider'),
        ),
    ]
