# Generated by Django 2.2.7 on 2019-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingday',
            name='end_time',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='start_time',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
