# Generated by Django 2.2.7 on 2019-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0002_auto_20191129_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_1',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer_2',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
