# Generated by Django 2.2.7 on 2019-11-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0003_auto_20191129_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
    ]
