# Generated by Django 2.2.7 on 2019-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0004_remove_user_is_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
