# Generated by Django 2.2.7 on 2019-12-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0007_auto_20191201_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenimage',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
