# Generated by Django 2.2.7 on 2019-12-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenapp', '0009_auto_20191201_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenapp.User')),
            ],
        ),
    ]
